### ISSUE TITLE
Why is starboard message.author.bot here?

### ISSUE THREAD

**Issue by Murky-MoMo** [JairusSW/Discord.ez#2]
in starboardAdd.js, there is `if(message.author.bot) return` what is the purpose of this? 
to keep a bot message from being star-ed? 
if it's to keep a bot from *adding a star*, then it would be user.bot as the reactor is `user`
also you don't need to upload node-modules

**Comment by JairusSW** [comment]
Ooh, thank you! 😁 I didn't catch that! (Fixing it rn)
